#!/bin/bash

pattern="${1:-jpg}"

# Meaning: (-i any)          all interface,
#          (-R http.request) show only http requests
#          (-T fields)       print out designated fields
#          (-e http.host)    print this
#          (-e http.request.uri) print this
#          (-l) do not buffer

tshark -i any -R http.request -T fields -e http.host -e http.request.uri -l 2>/dev/null \
	| sed -r "/${pattern}/ { s/[ \t]//g; s/^/http:\/\//; p}; d"

